apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
  namespace: default

spec:
  replicas: 2

  selector:
    matchLabels:
      app: my-app

  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: rajat431/my-java-app:af560369a2d16a04e873456a97ed11b16c1a4748
          ports:
            - containerPort: 8080